apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      name: http

---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          env:
            - name: MONGO_INITDB_DATABASE  # Setting Database name
              value: orderService
            - name: MONGO_INITDB_ROOT_USERNAME # Setting Database password
              value:
            - name: MONGO_INITDB_ROOT_PASSWORD # Setting Database password
              value:
          ports:
            - containerPort: 27017
              name: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: LoadBalancer
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8084
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: myapp
          image: order:0.0.1
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL  # Setting Database name
              value: mongodb://mongodb:27017/orderService
            - name: MONGO_INITDB_ROOT_USERNAME
              value:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

