version: '3.5'

services:
  app:
    build: ./
    container_name: 'commentar-app'
    ports:
      - "8085:8085"
    depends_on:
      - neo4j
    environment:
      DATASOURCE_URI: bolt://neo4j-db:7687
      DATASOURCE_USERNAME: neo4j
      DATASOURCE_PASSWORD: neo4j12345678910
  neo4j:
    image: 'neo4j:latest'
    container_name: 'neo4j'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo4j12345678910"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.\\\*,gds.
