apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: LoadBalancer
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7687
      name: http

---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - image: neo4j
          name: neo4j
          ports:
            - containerPort: 7687
              name: neo4j

---
apiVersion: v1
kind: Service
metadata:
  name: commentar
  labels:
    app: commentar
spec:
  type: LoadBalancer
  selector:
    app: commentar
  ports:
    - protocol: TCP
      port: 8085
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentar
spec:
  selector:
    matchLabels:
      app: commentar
  replicas: 1
  template:
    metadata:
      labels:
        app: commentar
    spec:
      containers:
        - name: myapp
          image: commentar:0.0.1
          ports:
            - containerPort: 8085

