version: '3.5'

services:
  app:
    build: ./
    container_name: 'cart-app'
    ports:
      - "8083:8083"
    depends_on:
      - db
    links:
      - db

  db:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

