version: '3.5'

services:
  app:
    build: ./
    container_name: 'cart-app'
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=mongodb://db:27017/cartService

  db:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cartService
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

