version: '3.5'

services:
  app:
    build: ./
    container_name: 'elasticsearch-app'
    ports:
      - "8086:8086"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.14.0'
    container_name: 'elasticsearch'
    environment:
      - cluster.name=elasticSearchService
      - discovery.type=single-node
      - xpack.security.enabled=false
      - KAFKA_BOOTSTRAP_SERVER=localhost:9092
    ports:
      - "9200:9200"

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.14.0
#    container_name: logstash
#    volumes:
#      - ./logstash-config:/usr/share/logstash/pipeline
#    depends_on:
#      - elasticsearch
