apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9092
      name: http

---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch
          name: elasticsearch
          ports:
            - containerPort: 9092
              name: elasticsearch

---
apiVersion: v1
kind: Service
metadata:
  name: elasticSearchService
  labels:
    app: elasticSearchService
spec:
  type: LoadBalancer
  selector:
    app: elasticSearchService
  ports:
    - protocol: TCP
      port: 8086
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticSearchService
spec:
  selector:
    matchLabels:
      app: elasticSearchService
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticSearchService
    spec:
      containers:
        - name: myapp
          image: elasticsearch:0.0.1
          ports:
            - containerPort: 8086

