version: '3'

services:
  mysql:
    image: mysql:8.0.28
    container_name: 'java-mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=2301003120701
      - MYSQL_DATABASE=oauthService
      - MYSQL_PASSWORD=2301003120701

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8081:8081"

