version: '3.5'

services:
  app:
    build: ./
    container_name: 'product-app'
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2301003120701
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_PASSWORD=2301003120701'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=productService'
    ports:
      - "5432:5432"
