apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15
          name: postgres
          env:
            - name: POSTGRES_DB
              value: productService
            - name: POSTGRES_PASSWORD
              value: "2301003120701"
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres

---
---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8082
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: myapp
          image: product:0.0.1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL  # Setting Database name
              value: jdbc:postgresql://postgres:5432/productService
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2301003120701"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
