apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      name: http

---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_DATABASE  # Setting Database name
              value: oauthService
            - name: MYSQL_ROOT_PASSWORD # Setting Database password
              value: "2301003120701"
          ports:
            - containerPort: 3306
              name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    app: oauth
spec:
  type: LoadBalancer
  selector:
    app: oauth
  ports:
    - protocol: TCP
      port: 8081
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: myapp
          image: oauth:0.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL  # Setting Database name
              value: jdbc:mysql://mysql:3306/oauthService
            - name: MYSQL_ROOT_PASSWORD # Setting Database password
              value: "2301003120701"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "2301003120701"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
